### ISSUE TITLE
Remove Settings button

### ISSUE THREAD

**Issue by sgiuij** [sgiuij/streamflow_prediction#3]
i. We will remove the setting tab.
ii. We may do one of the below adjustments to the inner start/end time frame selection:
1. set a dead inner start/end time, only one bullet is move when animating. 
OR 2. keep the option of selecting the inner start/end time, but only on the slider itself
(So either way we are getting rid of the setting tab)
iii. remove header bar (home)

**Comment by contineu0818** [comment]
> keep the option of selecting the inner start/end time

This plan is easier to carry out, because the time range on slider bar is bind with the map layer. We need taker a manual convert if use only one bullet.
