### ISSUE TITLE
Mean graph on pop up page

### ISSUE THREAD

**Issue by sgiuij** [sgiuij/streamflow_prediction#5]
a graph with mean (volume/time) over the time period displays on the pop up page.
Based on our conversation we can query once a day or however frequency that would make sense. We can decide that when we get to try one out, but definitely doesn't have to be as accurate as every second or anything close.

**Comment by contineu0818** [comment]
@sgiuij The time interval on chart is setting by `RequestFeatureUtil.interval`, you could change it if necessary.
